name: qr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^14.8.1
  local_auth: ^2.3.0
  shared_preferences: ^2.5.2
  uuid: ^4.4.2
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
