name: qr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.5.4

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^14.8.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.3.0
  mobile_scanner: ^6.0.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  uuid: ^4.4.2
  flutter_native_splash: ^2.4.4
  flutter_bloc: ^9.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#42a5f5"
  image: assets/icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/
